const translate = {
  th: {
    'app.viewAll': 'ดูทั้งหมด',
    'list.create': 'สร้างข่าวสาร',
    'list.search': 'ค้นหา',
    'list.seeDetails': 'ดูรายละเอียด',
    'create.add': 'เพิ่ม',
    'view.details': 'รายละเอียด',
    copyright: 'สงวนลิขสิทธิ์ ให้กับพี่เพชร และเบลเท่านั้น',
    home: 'หน้าแรก',
    news: 'ข่าวสาร',
    title: 'ชื่อเรื่อง',
    category: 'หมวดหมู่',
    all: 'ทั้งหมด',
    updatedAt: 'วันที่แก้ไข',
    edit: 'แก้ไข',
    save: 'บันทึก',
    cancel: 'ยกเลิก',
    publishAt: 'วันที่เปิดให้ใช้งาน',
    thai: 'ภาษาไทย',
    english: 'ภาษาอังกฤษ',
  },
  en: {
    'app.viewAll': 'View All',
    'list.create': 'Create News',
    'list.search': 'Search',
    'list.seeDetails': 'See Details',
    'create.add': 'Add',
    'view.details': 'Details',
    copyright: "P'Petch and Belle. All Right Reserved.",
    home: 'Home',
    news: 'News',
    title: 'Title',
    category: 'Category',
    all: 'All',
    updatedAt: 'Updated At',
    edit: 'Edit',
    save: 'Save',
    cancel: 'Cancel',
    publishAt: 'Publish At',
    thai: 'Thai',
    english: 'English',
  },
}

export default translate
